version: '3'

services:
  # Flask Web Server
  web-server:
    build:
      context: ./server
    command: gunicorn -w 4 --bind 0.0.0.0:5000 resume:app
    ports:
      - 5000:5000       # Web server port

    volumes:
      - ./server/src:/app
    container_name: Resume_server

  
  